### ISSUE TITLE
"Inf" in sqlite DB causes upload failure

### ISSUE THREAD

**Issue by rkdarst** [denzilferreira/com.aware.plugin.ambient_noise#3]
Hi,

We've been looking at Aware and we think there is a problem with inf in the sqlite database of ambient noise.  I am not entirely sure this is it, but it seems like it's the most likely explanation so far.  Here is what I know:

First from Aware log (I'm not sure if the first line is related, probably not):
```
03-12 17:36:30.816  2450  5575 W CursorWindow: Window is full: requested allocation 76800 bytes, free space 18991 bytes, window size 2097152 bytes
03-12 17:36:30.950  2450  5575 W System.err: org.json.JSONException: Forbidden numeric value: Infinity
03-12 17:36:30.950  2450  5575 W System.err:    at org.json.JSON.checkDouble(JSON.java:25)
03-12 17:36:30.950  2450  5575 W System.err:    at org.json.JSONObject.put(JSONObject.java:218)
03-12 17:36:30.950  2450  5575 W System.err:    at com.aware.utils.WebserviceHelper.onHandleIntent(WebserviceHelper.java:319)
03-12 17:36:30.950  2450  5575 W System.err:    at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:68)
03-12 17:36:30.950  2450  5575 W System.err:    at android.os.Handler.dispatchMessage(Handler.java:102)
03-12 17:36:30.950  2450  5575 W System.err:    at android.os.Looper.loop(Looper.java:154)
03-12 17:36:30.950  2450  5575 W System.err:    at android.os.HandlerThread.run(HandlerThread.java:61)
```

Grepping through dumps of all database finds inf only in ``.  This is an excerpt of the .dump, showing header and then the row data:
```
CREATE TABLE plugin_ambient_noise (_id integer primary key autoincrement,timestamp real default 0,device_id text default '',double_frequency real default 0,double_decibels real default 0,double_rms real default 0,is_silent integer default 0,double_silence_threshold real default 0,blob_raw blob default null);
INSERT INTO "plugin_ambient_noise" VALUES(98,1488993041172.0,'4da957f3-fc68-45d0-afed-c0278da70aaf',0.0,Inf,0.0,0,50.0,X'00000000000000000000000... )
```
The `Inf` is in the decibels column.  Seems to have null data in most columns - maybe.  I haven't looked any more in-depth than this, tell me if you want me to.

It seems that Python allows an 'Infinity' literal that decodes to inf, but it is not standards-compliant and was able to receive inf values from another app (not that that's necessarily the right thing to do).

Thanks,
- Richard and @AnaTomomi

**Comment by denzilferreira** [comment]
Yes, amplitude is 0, log(0) = -Inf...
